Feat/external transference
guido732/santander-frio pull request #2
Opened 2020-02-23 23:03 UTC by guido732

2020-02-24 02:49 UTC, alazzuri commented on main.js
> +server.put("/account/operations/internaltransfer", getActiveUser, validateAmount, (req, res) => {
Le agregaría el V1 al inicio para respetar el criterio de los otros endpoints y mantener control de versiones. Cambiaria 'account' por 'accounts' por buenas prácticas de usar plurales en los endpoints.
Duda para pensar, accounts deberia ser un endpoint propio o venir derivado desde users, por ej, 'v1/users/accounts/operations...'?

2020-02-24 03:22 UTC, alazzuri requested changes

2020-02-24 03:22 UTC, alazzuri commented on main.js
>  function findUser(userDni, res) {
Esta funcion y la función getActiveUser hacen cosas parecidas. Podriamos unificar y usar una sola para todo?

2020-02-24 03:22 UTC, alazzuri commented on main.js
> +server.put("/account/operations/internaltransfer", getActiveUser, validateAmount, (req, res) => {
Le agregaría el V1 al inicio para respetar el criterio de los otros endpoints y mantener control de versiones. Cambiaria 'account' por 'accounts' por buenas prácticas de usar plurales en los endpoints.
Duda para pensar, accounts deberia ser un endpoint propio o venir derivado desde users, por ej, 'v1/users/accounts/operations...'?

2020-02-24 03:22 UTC, alazzuri commented on main.js
> +server.put("/account/operations/externaltransfer", getActiveUser, validateAmount, (req, res) => {
Mismo comentario que mas arriba respecto del V1, accounts y el path.

2020-02-24 03:22 UTC, alazzuri commented on main.js
> +	console.log(originUser, destinationUser);
Borrar este console.log

2020-02-24 03:22 UTC, alazzuri commented on main.js
> +	return accounts.filter(account => account.accounts.find(acc => acc.accountNumber === accountNumber))[0];
Aca dentro del filter quizas seria mejor poner (user => user.accounts...) porque segun entiendo el filter itera sobre los usuarios y de ahi entra en accounts de c/u.

2020-02-25 14:38 UTC, guido732 commented on main.js
> +server.put("/account/operations/internaltransfer", getActiveUser, validateAmount, (req, res) => {
Modificado.
Me parece bien lo de tener users como padre, tiene sentido como estructura.

2020-02-25 14:38 UTC, guido732 commented on main.js
> +	console.log(originUser, destinationUser);
ups

2020-02-25 14:38 UTC, guido732 commented on main.js
> +server.put("/account/operations/externaltransfer", getActiveUser, validateAmount, (req, res) => {
Resuelto!

2020-02-25 14:58 UTC, guido732 commented on main.js
> +	return accounts.filter(account => account.accounts.find(acc => acc.accountNumber === accountNumber))[0];
Es que necesito tomar todas las accounts y sobre eso iterar sobre las cuentas que tiene, por eso el nesting de funciones no es que parto de una única cuenta, estoy tomando todas.

2020-02-25 15:21 UTC, alazzuri approved these changes

2020-02-25 15:21 UTC, merged